### ISSUE TITLE
Fix icons overlaping text

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#10]
date selectors

**Comment by funblaster22** [comment]
![Screenshot_20240121-114126~2.png](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/7257bd25-371a-45a7-a7e7-93a8bf4693d4)

There's also a bit more padding on the left and right then I would like

**Comment by funblaster22** [comment]
![image](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/4fea4578-ea02-46bc-a6c5-ee1e6797a177)

Also this happened on the iPhone SE simulator in Chrome

**Comment by lectrician1** [comment]
This will be solved by #6 so.
