### ISSUE TITLE
Improve homepage layout with created and responded events

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#20]

**Comment by funblaster22** [comment]
This is kind of vague. I believe I might have fixed some stuff in 025989e7914f328f34f76002812a49e77d57d5e4 by limiting the width of the first component.

**Comment by funblaster22** [comment]
I got clarification: try out a grid or flex, something to balance them out from the left

**Comment by funblaster22** [comment]
What do you think? I thought making it perfectly centered would be too weird, so I set a max width and centered that container

![image](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/a9f1b821-e540-4ee9-9169-02542b5936e1)

**Comment by lectrician1** [comment]
Looks good!
