### ISSUE TITLE
Allow filtering/coloring of individual responses on the availability matrix

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#26]

**Comment by lectrician1** [comment]
What if instead of blending the colors we put them side-by-side in cells?

**Comment by funblaster22** [comment]
Any better (ignoring my questionable graphic design skills)?
![demo 2](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/4f19b4cd-3ee0-4bc8-8c75-5921980571f6)

**Comment by lectrician1** [comment]
Yes. Colors shoul remain in the same order though (so green is always to the right of red)

**Comment by funblaster22** [comment]
Here's what this looks like implemented

![image](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/c571c053-ec33-4b21-9486-84ba72fa9ce2)

**Comment by lectrician1** [comment]
Looks great! We should have this view togglable from the normal view.

**Comment by lectrician1** [comment]
providing the separated might like outlook does could be an option too?
![image](https://github.com/MeetAsOne/MeetAsOne/assets/22477298/0c4ae335-fd2b-4c8b-a260-2f1b92444106)
