### ISSUE TITLE
Remove year from dates in availability matrix

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#37]
Year takes up too much space in each column. add it like above

![image](https://github.com/MeetAsOne/MeetAsOne/assets/22477298/d84e1cbc-d8ab-4837-926d-1a777be59e73)

**Comment by lectrician1** [comment]
partially solved

**Comment by funblaster22** [comment]
I think this got fixed a little while ago, not sure what commit
