### ISSUE TITLE
horizontal/rectangular selection

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#43]
Just realized why when2meet does this. Many times you know that every day of the week you are available X to Y time so this makes it easier for users to fill out

**Comment by funblaster22** [comment]
Fixes #35

**Comment by funblaster22** [comment]
[This repo](https://github.com/bibekg/react-schedule-selector) does what we want, so we can look to for inspiration

**Comment by funblaster22** [comment]
jk, there might still be some bugs here, like not saving when removing availability

**Comment by funblaster22** [comment]
I've noticed it works for blocks that were created in that session, but not existing blocks

**Comment by lectrician1** [comment]
The behavior seems to work correctly to me

**Comment by lectrician1** [comment]
#53 better describes current issue that may have been caused by this implementation
