### ISSUE TITLE
Nothing selectable upon creating new event

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#5]
Likely caused by when the syncing of your availability and the group availability handler was added.

**Comment by funblaster22** [comment]
This is when you can't do anything immediately after creating a new event. I reset to before I made the "Preview action on group calendar" commit (bad5dc70ff812e1e699cf394af191d3e288f0866) and it works just fine, confirming Seth's suspicions

**Comment by funblaster22** [comment]
Just a thought worth looking into: this could be caused by the availability `writable` for group calendar not having the date & array fields (it is an empty object `{}`), so populate it with empty data for the date range

**Comment by funblaster22** [comment]
Ok, so b4d2d1a16279ac3730404e7f60edd39f5d60fada works by copying fields that exist from merge source to destination, but this has the unintended side effect of publishing irrelevant dates to the database
