### ISSUE TITLE
clear availability doesn't clear on group availability

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#51]
I'm Seth. there shouldn't be this intersection

![image](https://github.com/MeetAsOne/MeetAsOne/assets/22477298/d82187e3-97c3-452f-9692-381363a0467c)

**Comment by lectrician1** [comment]
i guess this requires subscripptions

**Comment by lectrician1** [comment]
idk

**Comment by funblaster22** [comment]
Could you add the link to this and some context as to how this happened? Or we could talk tomorrow
