### ISSUE TITLE
Add load saved availability button

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#53]
It's a confusing mechanic to automatically load the saved availability when the user may not know where it has come from.

Additionally, if I delete my name stored in the browser, and reload the page, the saved availability currently loads and shows up on the group availability even though it's technically not saved. It's not until I click on the matrix that it will prompt for my name and save.

Adding a load button fixes this because it:
- allows someone to view an event without adding their name (we wouldn't have to prompt for it immediately)
- when clicking load saved availability it will prompt for their name if it doesn't exist
- users know how the whole saving availability mechanism works

**Comment by funblaster22** [comment]
What about #7?

**Comment by lectrician1** [comment]
Well, this overrides it
