### ISSUE TITLE
Replace Date Select component

### ISSUE THREAD

**Issue by funblaster22** [MeetAsOne/MeetAsOne#6]
It's incredibly inconsistent & doesn't allow for arbitrary dates

**Comment by funblaster22** [comment]
Okay, I think the reason for not working after HMR and navigations is due to the fact that there's linked JavaScript code. [The docs] say I need to ____. Honestly, I'm considering sticking with this and tweaking it to our needs, as it already looks nice (surprisingly hard criteria to find on the internet). Here's what I found:

- https://github.com/t1m0n/air-datepicker: Nice b/c the time is attached to the date picker component, so this can allow easier implementation of #14. Implemented in vanilla js, not Svelte. Also has a range feature, probably strongest candidate
- https://svelte.dev/repl/f391b3186f804fb0bb0931e73388553a?version=3.46.4: little buggy, no range feature, but all the code is there and I can understand it, which might make extending it easier

**Comment by lectrician1** [comment]
Okay, all of those are bad. best thing i found today is https://mobiscroll.com/date-time-picker-calendar but it's piad

i got this react thing for free but it doesn't have the mobile touch behavior i want
https://shahabyazdi.github.io/react-multi-date-picker/multiple/

i swear i remember thinking about date pickers for a previous project and there's just no good master ones. maybe we should make a package and save the world

**Comment by lectrician1** [comment]
_Actually_, we could use the React date picker or a date picker from another framework if we switch our backend to Astro JS...

Would require moving our parse calendar api to cloud first #61

**Comment by funblaster22** [comment]
Using React seems a little goofy since we would need to load the entire client library for a single date picker. Also, I'm not familiar with Astro, so I hope that wouldn't involve rewriting too much stuff. ([combining frameworks](https://www.youtube.com/watch?v=hBzlb5ZxsKo))

**Comment by lectrician1** [comment]
I mean, it does tree shaking 🤷 ... Converting doesn't look thatttt bad. Also the react component even supports other calendars than Gregorian.

I think it would probably take more time to create our own than switch...

**Comment by funblaster22** [comment]
Now using flatpickr
