### ISSUE TITLE
Replace logo on homepage

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#69]
it's not an svg and a bit blurry. unfortunatly unacceptable

![image](https://github.com/MeetAsOne/MeetAsOne/assets/22477298/6c381fe5-b836-43a6-b00b-15dcb21a218f)

**Comment by lectrician1** [comment]
We should have one of those scrolling animations that switches when2meet with lettucemeet, and other alternatives!

**Comment by lectrician1** [comment]
https://codepen.io/parthv2/pen/BavyJog

**Comment by funblaster22** [comment]
![image](https://github.com/MeetAsOne/MeetAsOne/assets/53224922/e3f4f5aa-d706-4ee8-9c0a-fccda42d12a2)
