### ISSUE TITLE
Add "Sponsor needed" notice on website

### ISSUE THREAD

**Issue by lectrician1** [MeetAsOne/MeetAsOne#72]
On the homepage a notice like "Reach thousands of students and professionals with your brand here" should appear on both the homepage and event pages. It should then link to a website which would have details about sponsoring and an email to contact us with.

**Comment by lectrician1** [comment]
"Reach thousands of students and professionals with your brand [here](https://example.com)"

"here" should be italicized and have a link with the link icon thing that shows a link opens in a new tab.

**Comment by lectrician1** [comment]
The sponsor box at the bottom should not have rounded corners in the bottom

**Comment by funblaster22** [comment]
I'm going to link the whole text because [linking the word "here" is inaccessible](https://granicus.com/blog/why-click-here-links-are-bad/).
